package com.violinmaster.app.ui.theme

enum class AppLanguage {
    ENGLISH,
    SPANISH
}

object Localization {
    
    // Simple state flow inside ViewModel mapped here for convenience
    // Keys defined centrally to enforce clean practices
    private val en = mapOf(
        "app_name" to "Violin Master Pro",
        "tab_home" to "Home",
        "tab_lessons" to "Lessons",
        "tab_stats" to "Progress",
        "tab_settings" to "Settings",

        // Home Screen
        "welcome" to "Welcome back, Maestro!",
        "goal_progress" to "Daily Goal Progress",
        "no_goal" to "Setup a goal inside the settings panel.",
        "goal_achieved" to "Goal achieved! Incredible discipline! 🎉",
        "start_practice_now" to "START PRACTICE SESSION",
        "stop_save" to "STOP & SAVE SESSION",
        "quick_utilities" to "QUICK ASSISTANT TOOLS",
        "smart_tuner" to "Smart Tuner",
        "harmonic_metronome" to "Metronome",
        "tuner_desc" to "Play open strings to debug pitch & tuning",
        "metronome_desc" to "Configure tempo beat triggers & visual swing",
        "current_active_practice" to "Current Practice Topic:",
        "general_practice" to "General Practice",
        "daily_goal_title" to "DAILY GOAL",
        "active_practice_label" to "ACTIVE PRACTICE SESSION",
        "quick_tools_label" to "QUICK TOOLS",
        "recommended_drill_label" to "RECOMMENDED DRILL",
        "current_badge" to "CURRENT",
        "module_3_label" to "MODULE 3",
        "advanced_bowing_title" to "Advanced Bowing Techniques",
        "advanced_bowing_desc" to "Mastering the 'Détaché' and 'Martelé' strokes for cleaner transitions and dynamic range.",
        "save_and_log_button" to "Save & Log",
        "discard_button" to "Discard",
        "practicing_now_label" to "PRACTICING NOW",
        "resume_practice_button" to "RESUME PRACTICE",
        "cancel_button" to "CANCEL",
        "save_practice_cd" to "Save Practice",
        "cancel_practice_cd" to "Cancel Practice",

        // Settings Screen
        "settings_title" to "Maestro Configuration",
        "language_select" to "APPLICATION LANGUAGE",
        "lang_en" to "English (US)",
        "lang_es" to "Español (ES)",
        "daily_goal_label" to "DAILY MINUTES GOAL",
        "ref_pitch_label" to "REFERENCE CONCERT PITCH (Hz)",
        "auth_role_label" to "LOGGED USER PROFILE",
        "change_role_btn" to "Switch or Log Out Profile",
        "delete_data" to "FACTORY RESET PRACTICE LOGS",
        "reset_success" to "Logs flushed successfully.",
        "active_session_label" to "ACTIVE SESSION",
        "seed_db_title" to "EXPLORE SAMPLE HISTORY LOGS",
        "seed_db_desc" to "Populates 7 days of practice sessions into the local database to preview the weekly charts and metrics instantly.",
        "seed_db_button" to "Seed 7-Day Simulated Practice Logs",
        "violin_tips_title" to "VIOLIN METICULOUS PRACTICE TIPS",
        "violin_tips_text" to "• Warm-up Bowing: Spend 5 minutes on slow open-strings before playing exercises. Focus on matching straight bowing to the bridge.\n\n• Intonation Checks: Use the Tuner to test your finger placements in higher positions periodically. Your ears will develop quicker.\n\n• Metronome tempo progression: When practicing scales or tricky measures, reduce the Metronome BPM to 60. Increase tempo only once you repeat the sequence perfectly 5 times.",

        // Login & Roles
        "login_required" to "Violin Studio Authentication",
        "username_label" to "User Account ID",
        "password_label" to "Private Cryptographic Pin",
        "role_label" to "Choose Academic Role",
        "role_teacher" to "Teacher/Instructor",
        "role_student" to "Student/Apprentice",
        "role_freelancer" to "Freelancer/Autodidact",
        "birth_year_label" to "Year of Birth",
        "birth_year_hint" to "Select your birth year",
        "error_birth_year_invalid" to "Please select a valid birth year",
        "register_desc" to "Create account with a secure passcode",
        "login_info_desc" to "Enter credentials to unlock lesson archives",
        "pin_hint" to "Enter 4 digits",
        "btn_login" to "Log In Account",
        "btn_register" to "Register Profile",
        "switch_to_reg" to "Don't have an account? Register here",
        "switch_to_log" to "Already have an account? Sign In",

        // Teacher Panel
        "teacher_dashboard_title" to "Teacher Command Studio",
        "your_code_label" to "Your Teacher Invite Code:",
        "copy_code_tip" to "Students use this code upon registering to link to you.",
        "send_assignment" to "ASSIGN NEW OBJECTIVE",
        "select_student" to "Designee Student:",
        "all_students" to "All Connected Students",
        "assignment_title_hint" to "Assignment Title (e.g. Vibrato Slow-Wave)",
        "assignment_desc_hint" to "Warm-up steps, repetitions & goals...",
        "attach_video_label" to "Attach Optional Demonstration Video:",
        "attachment_allowed" to "Attach Video (Max 3 Mins)",
        "detach_video" to "Remove Video Attachment",
        "duration_sec_label" to "Simulated Video Length (Seconds):",
        "video_time_limit" to "Video exceeds maximum length of 3 minutes (180s)!",
        "btn_submit_assignment" to "Disseminate Assignment",
        "predefined_templates" to "PREDEFINED LESSON PLAN TEMPLATES",
        "temp_posture" to "Shoulder and Chinrest Alignment Checks",
        "temp_res" to "Sympathetic Resonance Checks in D Major",
        "temp_bounce" to "Spiccato Wood Equilibrium Gravity Bounce",
        "sent_assignments_log" to "DELIVERED ASSIGNMENTS LOG",
        "delete_task" to "Delete Task",

        // Student Panel
        "student_dashboard_title" to "Student Practice Hub",
        "link_teacher_title" to "LINK INSTRUCTOR CODE",
        "link_teacher_desc" to "Input your instructor's invite code to fetch assigned tasks.",
        "input_code_hint" to "Enter Teacher Code (e.g. TEACH-XXXX)",
        "btn_link_teacher" to "Link Instructor",
        "linked_to_teacher" to "Connected and verified with: ",
        "instructor_name_placeholder" to "Instructor",
        "no_assignments" to "Your teacher hasn't published any assignments yet. Keep practicing with open tools!",
        "assigned_by" to "Assigned by: ",
        "btn_complete" to "Submit Completion Log",
        "completed_tag" to "COMPLETED",
        "play_sim_video" to "Play Demonstration Video",
        "assignments_section_title" to "YOUR ACADEMIC ASSIGNMENTS",

        // Freelancer Screen
        "lessons_header_freelancer" to "Violin Curriculum",

        // General Messages
        "error_username_empty" to "Username cannot be empty.",
        "error_pin_length" to "Passcode PIN must be exactly 4 digits.",
        "error_login_failed" to "Incorrect username or security PIN.",
        "error_user_exists" to "User already registered. Please login.",
        "success_register" to "Account secured! Log in now.",

        // New scoring & rankings
        "daily_tasks_title" to "DAILY TASKS",
        "leaderboard_title" to "GLOBAL LEADERBOARD",
        "rank_label" to "Rank",
        "points_label" to "Points",
        "points_suffix" to "pts",
        "skill_level_label" to "DIFFICULTY LEVEL",
        "skill_beginner" to "Beginner",
        "skill_intermediate" to "Intermediate",
        "skill_advanced" to "Advanced",
        "attempts_needed_title" to "Task Completed!",
        "attempts_needed_subtitle" to "How many attempts did you need?",
        "attempt_1" to "1 attempt (100 pts)",
        "attempt_2" to "2 attempts (75 pts)",
        "attempt_3" to "3 attempts (50 pts)",
        "attempt_4" to "4+ attempts (25 pts)",
        "confirm_completion" to "CONFIRM COMPLETION",
        "start_task" to "START",
        "completed_btn" to "COMPLETED",
        "analytics_sub_tab" to "ANALYTICS",
        "ranking_sub_tab" to "LEADERBOARD",
        "level_title" to "Skill Level",

        // Tuner Screen
        "smart_tuner_header" to "SMART TUNER",
        "tuner_subtitle" to "Fine Tuning & Pitch Reference",
        "auto_string_detect" to "AUTO STRING DETECT",
        "auto_detect_desc" to "Locks frequencies automatically",
        "mic_permission_error" to "Microphone permission required for tuning",
        "select_string_prompt" to "Select a string below",
        "reference_playback" to "Reference Playback",
        "perfectly_in_tune" to "PERFECTLY IN TUNE",
        "stop_synth_sound" to "Stop Synth Sound",
        "play_reference_tone" to "Play Reference Tone",
        "start_listen_mode" to "START ACCURATE LISTEN MODE",
        "stop_mic_listen" to "STOP MICROPHONE LISTEN",
        "cents_flat" to "FLAT",
        "cents_sharp" to "SHARP",

        // Metronome Screen
        "metronome_header" to "METRONOME",
        "metronome_subtitle" to "Rhythmic Pulse Trainer",
        "bpm_tempo_label" to "BPM (TEMPO)",
        "tap_tempo_button" to "TAP TEMPO",
        "time_signature_label" to "TIME SIGNATURE",
        "downbeat_accent_label" to "DOWNBEAT ACCENT",
        "accent_on" to "ACCENT ON",
        "accent_off" to "ACCENT OFF",
        "pause_pulse" to "PAUSE PULSE",
        "play_metronome" to "PLAY METRONOME",
        "decrement_bpm_cd" to "Decrement BPM",
        "increment_bpm_cd" to "Increment BPM",

        // Masterclass / Auth
        "app_title_auth" to "VIOLIN STUDIO PRO",
        "shield_security_logo" to "Shield Security Logo",

        // Stats Screen
        "practice_streak" to "PRACTICE STREAK",
        "daily_average" to "DAILY AVERAGE",
        "practice_drill_trend" to "PRACTICE DRILL TREND (MINS)",
        "completed_practice_journal" to "COMPLETED PRACTICE JOURNAL",
        "empty_log_book" to "Your log book is empty. Complete a practice module or sound tuning reference to log stats!",

        // Lessons Screen
        "learning_journey_progress" to "LEARNING JOURNEY PROGRESS",
        "modules_passed" to "Modules Passed",
        "total_bow_time" to "Total bow time",
        "level_prefix" to "Level:",
        "minutes_practiced" to "m practiced",
        "stage_learning_objectives" to "STAGE LEARNING OBJECTIVES:",
        "included_core_drills" to "INCLUDED CORE DRILLS:",
        "select_current_string" to "SELECT CURRENT VIOLIN STRING:",
        "string_label" to "String",
        "virtual_fingerboard" to "VIRTUAL FINGERBOARD GRAPHIC (1st Position Tapes):",
        "position_relative_tape" to "Position relative tape",
        "string_target" to "String: Target",
        "frequency_match" to "Frequency match:",
        "listen_and_match" to "Listen and match the pitch with your physical violin first position fingers.",

        // Extra hardcoded strings extracted during production-ready refactor
        "modules_progress_format" to "%d of %d Modules Passed",
        "total_bow_time_format" to "Total bow time: %dm practiced",
        "level_format" to "Level: %s",
        "syllabus_suffix" to "%s SYLLABUS",
        "minutes_practiced_format" to "%dm practiced",
        "lesson_completed_button" to "Completed",
        "mark_done_button" to "Mark Done",
        "practicing_label" to "PRACTICING",
        "drill_time_button" to "DRILL TIME",
        "string_label_format" to "%s String",
        "note_frequency_format" to "%s (%d Hz)",
        "string_target_format" to "%s-String: Target %s",
        "frequency_match_format" to "Frequency match: %s Hz",
        "video_instructor_prefix" to "Instructor: ",
        "video_duration_prefix" to "Video Duration: ",
        "secure_time_format" to "SECURE TIME: %02d:%02d",
        "close_stream_button" to "Close Stream",
        "secure_stream_cdn_label" to "AES-256 CDN Stream",
        "practice_log_format" to "practiced %d mins",
        "delete_log_cd" to "Delete practice log",
        "student_prefix" to "STUDENT: ",
        "streak_days_format" to "%d Days",
        "average_format" to "%.1f m",
        "video_demo_format" to "Video Demo: %ds",
        "stats_analytics_title" to "Weekly Practice Balance",
        "stats_leaderboard_title" to "Global Rankings",
        "pending_label" to "PENDING",
        "video_title_placeholder" to "Video Title (e.g. Vibrato Bowing Guide)",
        "resource_target_protocol" to "Resource Target Protocol:",
        "access_ticket_expiry" to "Access Ticket Lease Expiry Epoch:",
        "lease_valid" to " (Lease valid)",
        "dynamic_crypto_nonce" to "Dynamic Crypto Nonce Code:",
        "hmac_sha256_signature" to "HMAC SHA-256 Access Ticket Signature:",
        "encouragement_seed" to "Seed your skills! Focus on straight open string bows.",
        "encouragement_warm" to "Warm resonance growing! Practice shifts carefully.",
        "encouragement_habits" to "Outstanding habits! Your double stops sound magnificent.",
        "encouragement_virtuoso" to "Virtuoso level! A master academic scholar of the acoustic violin.",

        // TeacherStudentWorkspace
        "active_label" to "ACTIVE",
        "no_previous_history" to "No previous history logs.",
        "attached_video_label_short" to "Attached video:",

        // Chat
        "chat_title" to "Chat",
        "chat_button" to "Open Chat",
        "chat_input_hint" to "Type a message...",
        "chat_empty" to "No messages yet. Start the conversation!",
        "chat_send" to "Send message",
        "chat_today" to "Today",
        "chat_yesterday" to "Yesterday",
        "chat_attachment_video" to "Video attachment",
        "back_button" to "Back",

        // Video Recording & Upload
        "video_record" to "Record",
        "video_stop" to "Stop",
        "video_recording" to "Recording...",
        "video_compressing" to "Compressing video...",
        "video_uploading" to "Uploading...",
        "video_send" to "Send to Chat",
        "video_cancel" to "Cancel",
        "video_retry" to "Retry",
        "video_record_button" to "Record Video",
        "video_upload_success" to "Video uploaded successfully!",
        "video_time_remaining" to "Time remaining:",
        "video_permission_title" to "Camera Access Needed",
        "video_permission_rationale" to "Camera access is needed to record practice demonstration videos for your students.",
        "video_permission_grant" to "Grant Access",
        "video_permission_deny" to "Not Now",
        "video_permission_required" to "Camera permission required to record videos. Please grant access in Settings.",

        // Face Blur — Minor Student Protection (REQ-BLR-005, REQ-BLR-007)
        "blur_processing" to "Protecting identity...",
        "blur_progress" to "Processing frame %1\$d/%2\$d",
        "blur_warning" to "Face blur could not be applied. Video sent without blur.",
        "blur_disabled" to "Face blur not required (adult user)",

        // MasterclassTab
        "secure_student_pin" to "SECURE STUDENT ACCOUNT PIN",
        "secure_pin_desc" to "Create a master numeric passcode. Passwords are never stored in plain-text. They are hashed cryptographically with a unique secure salt to ensure extreme user data privacy.",
        "enter_vault_pin" to "ENTER PRIVATE VAULT PIN",
        "vault_pin_desc" to "Locked Area: Premium masterclass modules require authorized decryption confirmation. Enter your four-digit secure account passcode.",
        "secure_video_decryption" to "SECURE VIDEO DECRYPTION LIVE",
        "authorized_access_confirmed" to "Authorized access is confirmed. Playback streams generate dynamic, cryptographically signed signed-ticket tokens with a 60-second automatic API expiration lease.",
        "academy_lecture_modules" to "ACADEMY LECTURE MODULES",
        "logout_vault" to "Logout Vault",
        "active_secure_stream" to "ACTIVE SECURE STREAM",
        "live_decrypting" to "LIVE DECRYPTING PLAYBACK... [OK]",
        "decrypt_interaction_logs" to "DECRYPT INTERACTION SECURITY LOGS",
        "secure_practice_protects" to "Secure practice protects videos against credential harvesting or sniffing. Here is the single-use signed streaming ticket generated for this lesson session.",
        "cdn_signature_verified" to "CDN signature validation status: [VERIFIED]",

        // Hardcoded messages in Spanish
        "theory_quest_quiz" to "Theory Quest & Quizzes",
        "theory_quiz_desc" to "Test your technical violin literacy and unlock performance badges with instant analysis.",
        "premium_masterclass" to "Premium Masterclass: Access restricted video tutorials secured via cryptographic salt & signed URL tickets.",
        "teacher_tab_desc" to "Distribute predefined curriculum plans, audit video demonstration bounds, and manage student accounts.",
        "student_tab_desc" to "View exercises assigned exclusively by your instructor, study tutorial videos, and track your progress.",
        "freelancer_tab_desc" to "Track your levels, complete explicit learning objectives, and start targeted bowing drills.",
        "verify_answer" to "VERIFY ANSWER",
        "next_question" to "NEXT QUESTION",
        "show_finished_summary" to "SHOW FINISHED SUMMARY",
        "theory_quiz_completed" to "Theory Quiz Completed!",
        "you_scored" to "You scored %d points out of 100",
        "theory_badge_title" to "Theory Academic Master Badge",
        "theory_badge_desc" to "Perfect technical literacy unlocked!",
        "try_again" to "TRY AGAIN",
        "v_excellent_guess" to "✓ Excellent Guess!",
        "x_correction" to "✗ Correction!"
    )

    private val es = mapOf(
        "app_name" to "Maestro de Violín Pro",
        "tab_home" to "Inicio",
        "tab_lessons" to "Lecciones",
        "tab_stats" to "Progreso",
        "tab_settings" to "Ajustes",

        // Home Screen
        "welcome" to "¡Bienvenido, Maestro!",
        "goal_progress" to "Meta Diaria de Práctica",
        "no_goal" to "Configura una meta diaria en la pestaña de ajustes.",
        "goal_achieved" to "¡Meta cumplida! ¡Disciplina increíble! 🎉",
        "start_practice_now" to "INICIAR SESIÓN DE PRÁCTICA",
        "stop_save" to "DETENER Y GUARDAR SESIÓN",
        "quick_utilities" to "HERRAMIENTAS AUXILIARES",
        "smart_tuner" to "Afinador Inteligente",
        "harmonic_metronome" to "Metrónomo",
        "tuner_desc" to "Toca cuerdas al aire para calibrar la entonación",
        "metronome_desc" to "Configura el tempo, silencios y movimiento visual",
        "current_active_practice" to "Tema de Práctica Activo:",
        "general_practice" to "Práctica General",
        "daily_goal_title" to "META DIARIA",
        "active_practice_label" to "SESIÓN DE PRÁCTICA ACTIVA",
        "quick_tools_label" to "HERRAMIENTAS RÁPIDAS",
        "recommended_drill_label" to "EJERCICIO RECOMENDADO",
        "current_badge" to "ACTUAL",
        "module_3_label" to "MÓDULO 3",
        "advanced_bowing_title" to "Técnicas Avanzadas de Arco",
        "advanced_bowing_desc" to "Dominando los golpes de arco 'Détaché' y 'Martelé' para transiciones más limpias y rango dinámico.",
        "save_and_log_button" to "Guardar y Registrar",
        "discard_button" to "Descartar",
        "practicing_now_label" to "PRACTICANDO AHORA",
        "resume_practice_button" to "REANUDAR PRÁCTICA",
        "cancel_button" to "CANCELAR",
        "save_practice_cd" to "Guardar Práctica",
        "cancel_practice_cd" to "Cancelar Práctica",

        // Settings Screen
        "settings_title" to "Configuraciones del Maestro",
        "language_select" to "IDIOMA DE LA APLICACIÓN",
        "lang_en" to "English (US)",
        "lang_es" to "Español (ES)",
        "daily_goal_label" to "META DIARIA DE MINUTOS",
        "ref_pitch_label" to "FRECUENCIA DEL CONCIERTO (Hz)",
        "auth_role_label" to "PERFIL DE USUARIO ACTIVO",
        "change_role_btn" to "Cerrar Sesión / Cambiar Perfil",
        "delete_data" to "RECO_RESET: BORRAR TODO EL HISTORIAL",
        "reset_success" to "Historial de práctica eliminado.",
        "active_session_label" to "SESIÓN ACTIVA",
        "seed_db_title" to "EXPLORAR REGISTROS DE PRÁCTICA",
        "seed_db_desc" to "Genera 7 días de sesiones de práctica en la base de datos local para previsualizar los gráficos y métricas semanales al instante.",
        "seed_db_button" to "Generar Registros de Práctica (7 Días)",
        "violin_tips_title" to "CONSEJOS METICULOSOS DE PRÁCTICA",
        "violin_tips_text" to "• Calentamiento de Arco: Dedica 5 minutos a cuerdas al aire lentas antes de los ejercicios. Concéntrate en mantener el arco recto y paralelo al puente.\n\n• Verificación de Entonación: Usa el Afinador para comprobar la colocación de los dedos en posiciones altas periódicamente. Tu oído se desarrollará más rápido.\n\n• Progresión con Metrónomo: Al practicar escalas o pasajes difíciles, reduce el BPM del Metrónomo a 60. Aumenta el tempo solo cuando repitas la secuencia perfectamente 5 veces.",

        // Login & Roles
        "login_required" to "Autenticación de Violin Studio",
        "username_label" to "ID de la Cuenta de Usuario",
        "password_label" to "PIN de Seguridad Privado",
        "role_label" to "Elige tu Rol Académico",
        "role_teacher" to "Profesor / Instructor",
        "role_student" to "Estudiante / Aprendiz",
        "role_freelancer" to "Freelancer / Autodidacta",
        "birth_year_label" to "Año de Nacimiento",
        "birth_year_hint" to "Selecciona tu año de nacimiento",
        "error_birth_year_invalid" to "Selecciona un año de nacimiento válido",
        "register_desc" to "Crea una cuenta con un PIN cifrado seguro",
        "login_info_desc" to "Inicia sesión para desbloquear las lecciones",
        "pin_hint" to "Introduce 4 dígitos",
        "btn_login" to "Iniciar Sesión",
        "btn_register" to "Registrar Cuenta",
        "switch_to_reg" to "¿No tienes cuenta? Regístrate aquí",
        "switch_to_log" to "¿Ya tienes cuenta? Inicia Sesión",

        // Teacher Panel
        "teacher_dashboard_title" to "Panel de Control del Instructor",
        "your_code_label" to "Tu Código de Invitación de Profesor:",
        "copy_code_tip" to "Los estudiantes usan este código al registrarse para vincularse contigo.",
        "send_assignment" to "ENVIAR NUEVA TAREA",
        "select_student" to "Asignar al estudiante:",
        "all_students" to "Todos los Estudiantes Vinculados",
        "assignment_title_hint" to "Título de la Tarea (ej. Vibrato Lento)",
        "assignment_desc_hint" to "Pasos de calentamiento, repeticiones y metas...",
        "attach_video_label" to "Adjuntar Video de Demostración Opcional:",
        "attachment_allowed" to "Adjuntar un Video (Máx 3 Minutos)",
        "detach_video" to "Quitar Video Adjunto",
        "duration_sec_label" to "Duración Regulada del Video (Segundos):",
        "video_time_limit" to "¡El video supera el límite de 3 minutos (180s)!",
        "btn_submit_assignment" to "Publicar y Enviar Tarea",
        "predefined_templates" to "PLANTILLAS DE LECCIONES PREDEFINIDAS",
        "temp_posture" to "Alineación y Calibración de Postura del Violín",
        "temp_res" to "Prácticas de Resonancia en Re Mayor",
        "temp_bounce" to "Punto de Equilibrio y Rebote del Arco (Spiccato)",
        "sent_assignments_log" to "HISTORIAL DE TAREAS ENVIADAS",
        "delete_task" to "Eliminar Tarea",

        // Student Panel
        "student_dashboard_title" to "Centro de Práctica del Estudiante",
        "link_teacher_title" to "VINCULAR CÓDIGO DEL PROFESOR",
        "link_teacher_desc" to "Escribe el código de invitación de tu profesor para recibir tus asignaciones.",
        "input_code_hint" to "Introduce el Código (ej. TEACH-XXXX)",
        "btn_link_teacher" to "Vincular Profesor",
        "linked_to_teacher" to "Conectado y verificado con: ",
        "instructor_name_placeholder" to "Instructor",
        "no_assignments" to "Tu profesor no ha enviado tareas aún. ¡Sigue practicando con las herramientas libres!",
        "assigned_by" to "Asignado por: ",
        "btn_complete" to "Marcar como Completado",
        "completed_tag" to "COMPLETADO",
        "play_sim_video" to "Reproducir Video de Demostración",
        "assignments_section_title" to "TUS TAREAS ACADÉMICAS",

        // Freelancer Screen
        "lessons_header_freelancer" to "Plan Curricular de Violín",

        // General Messages
        "error_username_empty" to "El ID de usuario no puede estar vacío.",
        "error_pin_length" to "El PIN debe ser exactamente de 4 dígitos.",
        "error_login_failed" to "ID de usuario o PIN de seguridad incorrecto.",
        "error_user_exists" to "El usuario ya está registrado. Inicie sesión.",
        "success_register" to "¡Cuenta registrada! Ya puedes iniciar sesión.",

        // New scoring & rankings
        "daily_tasks_title" to "TAREAS DIARIAS",
        "leaderboard_title" to "CLASIFICACIÓN GLOBAL",
        "rank_label" to "Puesto",
        "points_label" to "Puntos",
        "points_suffix" to "pts",
        "skill_level_label" to "NIVEL DE HABILIDAD",
        "skill_beginner" to "Principiante",
        "skill_intermediate" to "Intermedio",
        "skill_advanced" to "Avanzado",
        "attempts_needed_title" to "¡Tarea Completada!",
        "attempts_needed_subtitle" to "¿Cuántos intentos has necesitado?",
        "attempt_1" to "1 intento (100 pts)",
        "attempt_2" to "2 intentos (75 pts)",
        "attempt_3" to "3 intentos (50 pts)",
        "attempt_4" to "4+ intentos (25 pts)",
        "confirm_completion" to "CONFIRMAR",
        "start_task" to "COMENZAR",
        "completed_btn" to "COMPLETADO",
        "analytics_sub_tab" to "ESTADÍSTICAS",
        "ranking_sub_tab" to "CLASIFICACIÓN",
        "level_title" to "Nivel de Habilidad",

        // Tuner Screen
        "smart_tuner_header" to "AFINADOR INTELIGENTE",
        "tuner_subtitle" to "Afinación Precisa y Referencia de Tono",
        "auto_string_detect" to "DETECCIÓN AUTOMÁTICA DE CUERDA",
        "auto_detect_desc" to "Fija frecuencias automáticamente",
        "mic_permission_error" to "Se requiere permiso de micrófono para afinar",
        "select_string_prompt" to "Selecciona una cuerda abajo",
        "reference_playback" to "Reproducción de Referencia",
        "perfectly_in_tune" to "PERFECTAMENTE AFINADO",
        "stop_synth_sound" to "Detener Sonido Sintetizado",
        "play_reference_tone" to "Reproducir Tono de Referencia",
        "start_listen_mode" to "INICIAR MODO DE ESCUCHA PRECISA",
        "stop_mic_listen" to "DETENER ESCUCHA DEL MICRÓFONO",
        "cents_flat" to "BEMOL",
        "cents_sharp" to "SOSTENIDO",

        // Metronome Screen
        "metronome_header" to "METRÓNOMO",
        "metronome_subtitle" to "Entrenador de Pulso Rítmico",
        "bpm_tempo_label" to "BPM (TEMPO)",
        "tap_tempo_button" to "TAP TEMPO",
        "time_signature_label" to "COMPÁS",
        "downbeat_accent_label" to "ACENTO DEL PULSO",
        "accent_on" to "ACENTO ACTIVADO",
        "accent_off" to "ACENTO DESACTIVADO",
        "pause_pulse" to "PAUSAR PULSO",
        "play_metronome" to "INICIAR METRÓNOMO",
        "decrement_bpm_cd" to "Reducir BPM",
        "increment_bpm_cd" to "Aumentar BPM",

        // Masterclass / Auth
        "app_title_auth" to "VIOLIN STUDIO PRO",
        "shield_security_logo" to "Logo de Escudo de Seguridad",

        // Stats Screen
        "practice_streak" to "RACHA DE PRÁCTICA",
        "daily_average" to "PROMEDIO DIARIO",
        "practice_drill_trend" to "TENDENCIA DE PRÁCTICA (MINS)",
        "completed_practice_journal" to "DIARIO DE PRÁCTICA COMPLETADO",
        "empty_log_book" to "Tu libro de registro está vacío. ¡Completa un módulo de práctica o una referencia de afinación para registrar estadísticas!",

        // Lessons Screen
        "learning_journey_progress" to "PROGRESO DEL VIAJE DE APRENDIZAJE",
        "modules_passed" to "Módulos Aprobados",
        "total_bow_time" to "Tiempo total de arco",
        "level_prefix" to "Nivel:",
        "minutes_practiced" to "m practicados",
        "stage_learning_objectives" to "OBJETIVOS DE APRENDIZAJE:",
        "included_core_drills" to "EJERCICIOS INCLUIDOS:",
        "select_current_string" to "SELECCIONAR CUERDA ACTUAL:",
        "string_label" to "Cuerda",
        "virtual_fingerboard" to "DIAGRAMA VIRTUAL DEL DIAPASÓN (Cintas de 1ª Posición):",
        "position_relative_tape" to "Cinta de posición relativa",
        "string_target" to "Cuerda: Objetivo",
        "frequency_match" to "Frecuencia coincidente:",
        "listen_and_match" to "Escucha e iguala el tono con los dedos de tu violín físico en primera posición.",

        // Extra hardcoded strings — Spanish translations
        "modules_progress_format" to "%d de %d Módulos Aprobados",
        "total_bow_time_format" to "Tiempo total de arco: %dm practicados",
        "level_format" to "Nivel: %s",
        "syllabus_suffix" to "%s SÍLABO",
        "minutes_practiced_format" to "%dm practicados",
        "lesson_completed_button" to "Completado",
        "mark_done_button" to "Marcar Hecho",
        "practicing_label" to "PRACTICANDO",
        "drill_time_button" to "EJERCITAR",
        "string_label_format" to "Cuerda %s",
        "note_frequency_format" to "%s (%d Hz)",
        "string_target_format" to "Cuerda-%s: Objetivo %s",
        "frequency_match_format" to "Frecuencia coincidente: %s Hz",
        "video_instructor_prefix" to "Instructor: ",
        "video_duration_prefix" to "Duración del Video: ",
        "secure_time_format" to "TIEMPO SEGURO: %02d:%02d",
        "close_stream_button" to "Cerrar Transmisión",
        "secure_stream_cdn_label" to "Transmisión CDN AES-256",
        "practice_log_format" to "practicado %d mins",
        "delete_log_cd" to "Eliminar registro de práctica",
        "student_prefix" to "ESTUDIANTE: ",
        "streak_days_format" to "%d Días",
        "average_format" to "%.1f m",
        "video_demo_format" to "Video Demo: %ds",
        "stats_analytics_title" to "Balance Semanal de Práctica",
        "stats_leaderboard_title" to "Clasificación Global",
        "pending_label" to "PENDIENTE",
        "video_title_placeholder" to "Título del Video (ej. Guía de Vibrato)",
        "resource_target_protocol" to "Protocolo de Recurso Objetivo:",
        "access_ticket_expiry" to "Expiración del Ticket de Acceso:",
        "lease_valid" to " (Válido)",
        "dynamic_crypto_nonce" to "Código Criptográfico Dinámico:",
        "hmac_sha256_signature" to "Firma HMAC SHA-256 del Ticket:",
        "encouragement_seed" to "Planta tus habilidades. Concéntrate en arcos rectos de cuerdas al aire.",
        "encouragement_warm" to "La resonancia cálida crece. Practica los cambios con cuidado.",
        "encouragement_habits" to "Hábitos excepcionales. Tus dobles cuerdas suenan magníficas.",
        "encouragement_virtuoso" to "Nivel virtuoso. Un maestro académico del violín acústico.",

        // TeacherStudentWorkspace
        "active_label" to "ACTIVO",
        "no_previous_history" to "Sin registros de historial previos.",
        "attached_video_label_short" to "Video adjunto:",

        // Chat
        "chat_title" to "Chat",
        "chat_button" to "Abrir Chat",
        "chat_input_hint" to "Escribe un mensaje...",
        "chat_empty" to "Aún no hay mensajes. ¡Inicia la conversación!",
        "chat_send" to "Enviar mensaje",
        "chat_today" to "Hoy",
        "chat_yesterday" to "Ayer",
        "chat_attachment_video" to "Video adjunto",
        "back_button" to "Volver",

        // Video Recording & Upload
        "video_record" to "Grabar",
        "video_stop" to "Detener",
        "video_recording" to "Grabando...",
        "video_compressing" to "Comprimiendo video...",
        "video_uploading" to "Subiendo...",
        "video_send" to "Enviar al Chat",
        "video_cancel" to "Cancelar",
        "video_retry" to "Reintentar",
        "video_record_button" to "Grabar Video",
        "video_upload_success" to "¡Video subido exitosamente!",
        "video_time_remaining" to "Tiempo restante:",
        "video_permission_title" to "Acceso a la Cámara Requerido",
        "video_permission_rationale" to "Se necesita acceso a la cámara para grabar videos de demostración para tus estudiantes.",
        "video_permission_grant" to "Conceder Acceso",
        "video_permission_deny" to "Ahora No",
        "video_permission_required" to "Se requiere permiso de cámara para grabar videos. Concede acceso en Ajustes.",

        // Face Blur — Minor Student Protection (REQ-BLR-005, REQ-BLR-007)
        "blur_processing" to "Protegiendo identidad...",
        "blur_progress" to "Procesando frame %1\$d/%2\$d",
        "blur_warning" to "No se pudo aplicar el difuminado facial. Video enviado sin difuminar.",
        "blur_disabled" to "Difuminado no requerido (usuario adulto)",

        // MasterclassTab
        "secure_student_pin" to "PIN SEGURO DE CUENTA",
        "secure_pin_desc" to "Crea un código de acceso numérico maestro. Las contraseñas nunca se almacenan en texto plano. Se procesan criptográficamente con una sal única segura para garantizar la máxima privacidad de los datos del usuario.",
        "enter_vault_pin" to "INGRESAR PIN DE LA BÓVEDA",
        "vault_pin_desc" to "Área Bloqueada: Los módulos de clase magistral premium requieren confirmación de descifrado autorizado. Ingresa tu código de acceso seguro de cuatro dígitos.",
        "secure_video_decryption" to "DESCIFRADO SEGURO DE VIDEO EN VIVO",
        "authorized_access_confirmed" to "Acceso autorizado confirmado. Las transmisiones de reproducción generan tokens de tickets firmados criptográficamente con una caducidad automática de 60 segundos.",
        "academy_lecture_modules" to "MÓDULOS DE CONFERENCIAS ACADÉMICAS",
        "logout_vault" to "Cerrar Bóveda",
        "active_secure_stream" to "TRANSMISIÓN SEGURA ACTIVA",
        "live_decrypting" to "DESCIFRANDO REPRODUCCIÓN EN VIVO... [OK]",
        "decrypt_interaction_logs" to "REGISTROS DE INTERACCIÓN DE DESCIFRADO",
        "secure_practice_protects" to "La práctica segura protege los videos contra la captura de credenciales. Este es el ticket de transmisión firmado de un solo uso generado para esta sesión de lección.",
        "cdn_signature_verified" to "Estado de validación de firma CDN: [VERIFICADO]",

        // Hardcoded messages in Spanish
        "theory_quest_quiz" to "Misiones Teóricas y Cuestionarios",
        "theory_quiz_desc" to "Pon a prueba tus conocimientos técnicos de violín y desbloquea insignias con análisis instantáneo.",
        "premium_masterclass" to "Clase Magistral Premium: Accede a tutoriales de video restringidos mediante firma criptográfica de tickets de URL.",
        "teacher_tab_desc" to "Distribuye planes de estudio predefinidos, audita demostraciones en video y gestiona cuentas de estudiantes.",
        "student_tab_desc" to "Consulta los ejercicios que te ha asignado tu profesor en exclusiva, visualiza tutoriales en video y sigue tu evolución.",
        "freelancer_tab_desc" to "Haz un seguimiento de tus niveles, cumple directrices prácticas y comienza ejercicios avanzados de arco.",
        "verify_answer" to "VERIFICAR RESPUESTA",
        "next_question" to "SIGUIENTE PREGUNTA",
        "show_finished_summary" to "VER RESUMEN FINAL",
        "theory_quiz_completed" to "¡Cuestionario de Teoría Completado!",
        "you_scored" to "Has obtenido %d puntos de 100",
        "theory_badge_title" to "Insignia de Maestro Académico de Teoría",
        "theory_badge_desc" to "¡Conocimientos técnicos perfectos desbloqueados!",
        "try_again" to "INTENTAR DE NUEVO",
        "v_excellent_guess" to "¡✓ Respuesta Excelente!",
        "x_correction" to "¡✗ Corrección!"
    )

    fun get(key: String, language: AppLanguage): String {
        val bundle = if (language == AppLanguage.SPANISH) es else en
        return bundle[key] ?: en[key] ?: key
    }
}
