package com.violinmaster.app.ui.theme

object StringsSettings {
  val en = mapOf(
    "settings_title" to "Maestro Configuration",
    "language_select" to "APPLICATION LANGUAGE",
    "lang_en" to "English (US)",
    "lang_es" to "Español (ES)",
    "daily_goal_label" to "DAILY MINUTES GOAL",
    "ref_pitch_label" to "REFERENCE CONCERT PITCH (Hz)",
    "auth_role_label" to "LOGGED USER PROFILE",
    "change_role_btn" to "Switch or Log Out Profile",
    "delete_data" to "FACTORY RESET PRACTICE LOGS",
    "reset_success" to "Logs flushed successfully.",
    "active_session_label" to "ACTIVE SESSION",
    "seed_db_title" to "EXPLORE SAMPLE HISTORY LOGS",
    "seed_db_desc" to "Populates 7 days of practice sessions into the local database to preview the weekly charts and metrics instantly.",
    "seed_db_button" to "Seed 7-Day Simulated Practice Logs",
    "violin_tips_title" to "VIOLIN METICULOUS PRACTICE TIPS",
    "violin_tips_text" to "• Warm-up Bowing: Spend 5 minutes on slow open-strings before playing exercises. Focus on matching straight bowing to the bridge.\n\n• Intonation Checks: Use the Tuner to test your finger placements in higher positions periodically. Your ears will develop quicker.\n\n• Metronome tempo progression: When practicing scales or tricky measures, reduce the Metronome BPM to 60. Increase tempo only once you repeat the sequence perfectly 5 times.",

    "smart_tuner_header" to "SMART TUNER",
    "tuner_subtitle" to "Fine Tuning & Pitch Reference",
    "auto_string_detect" to "AUTO STRING DETECT",
    "auto_detect_desc" to "Locks frequencies automatically",
    "mic_permission_error" to "Microphone permission required for tuning",
    "select_string_prompt" to "Select a string below",
    "reference_playback" to "Reference Playback",
    "perfectly_in_tune" to "PERFECTLY IN TUNE",
    "stop_synth_sound" to "Stop Synth Sound",
    "play_reference_tone" to "Play Reference Tone",
    "start_listen_mode" to "START ACCURATE LISTEN MODE",
    "stop_mic_listen" to "STOP MICROPHONE LISTEN",
    "cents_flat" to "FLAT",
    "cents_sharp" to "SHARP",
    "config_button" to "⚙",
    "config_sheet_title" to "TUNER CONFIGURATION",
    "config_reference_pitch" to "Reference Pitch A4 (Hz)",
    "config_max_cents" to "Gauge Range (cents)",
    "config_save_preset" to "SAVE AS PRESET",
    "config_save_hint" to "Preset name",
    "config_my_presets" to "MY PRESETS",
    "config_no_presets" to "No saved presets yet",
    "config_load" to "LOAD",
    "config_delete" to "DELETE",
    "config_close" to "CLOSE",

    "metronome_header" to "METRONOME",
    "metronome_subtitle" to "Rhythmic Pulse Trainer",
    "bpm_tempo_label" to "BPM (TEMPO)",
    "tap_tempo_button" to "TAP TEMPO",
    "time_signature_label" to "TIME SIGNATURE",
    "downbeat_accent_label" to "DOWNBEAT ACCENT",
    "accent_on" to "ACCENT ON",
    "accent_off" to "ACCENT OFF",
    "pause_pulse" to "PAUSE PULSE",
    "play_metronome" to "PLAY METRONOME",
    "decrement_bpm_cd" to "Decrement BPM",
    "increment_bpm_cd" to "Increment BPM",

    "app_title_auth" to "VIOLIN STUDIO PRO",
    "shield_security_logo" to "Shield Security Logo",

    "video_record" to "Record",
    "video_stop" to "Stop",
    "video_recording" to "Recording...",
    "video_compressing" to "Compressing video...",
    "video_uploading" to "Uploading...",
    "video_send" to "Send to Chat",
    "video_cancel" to "Cancel",
    "video_retry" to "Retry",
    "video_record_button" to "Record Video",
    "video_upload_success" to "Video uploaded successfully!",
    "video_time_remaining" to "Time remaining:",
    "video_permission_title" to "Camera Access Needed",
    "video_permission_rationale" to "Camera access is needed to record practice demonstration videos for your students.",
    "video_permission_grant" to "Grant Access",
    "video_permission_deny" to "Not Now",
    "video_permission_required" to "Camera permission required to record videos. Please grant access in Settings.",

    "blur_processing" to "Protecting identity...",
    "blur_progress" to "Processing frame %1\$d/%2\$d",
    "blur_warning" to "Face blur could not be applied. Video sent without blur.",
    "blur_disabled" to "Face blur not required (adult user)"
  )

  val es = mapOf(
    "settings_title" to "Configuraciones del Maestro",
    "language_select" to "IDIOMA DE LA APLICACIÓN",
    "lang_en" to "English (US)",
    "lang_es" to "Español (ES)",
    "daily_goal_label" to "META DIARIA DE MINUTOS",
    "ref_pitch_label" to "FRECUENCIA DEL CONCIERTO (Hz)",
    "auth_role_label" to "PERFIL DE USUARIO ACTIVO",
    "change_role_btn" to "Cerrar Sesión / Cambiar Perfil",
    "delete_data" to "RECO_RESET: BORRAR TODO EL HISTORIAL",
    "reset_success" to "Historial de práctica eliminado.",
    "active_session_label" to "SESIÓN ACTIVA",
    "seed_db_title" to "EXPLORAR REGISTROS DE PRÁCTICA",
    "seed_db_desc" to "Genera 7 días de sesiones de práctica en la base de datos local para previsualizar los gráficos y métricas semanales al instante.",
    "seed_db_button" to "Generar Registros de Práctica (7 Días)",
    "violin_tips_title" to "CONSEJOS METICULOSOS DE PRÁCTICA",
    "violin_tips_text" to "• Calentamiento de Arco: Dedica 5 minutos a cuerdas al aire lentas antes de los ejercicios. Concéntrate en mantener el arco recto y paralelo al puente.\n\n• Verificación de Entonación: Usa el Afinador para comprobar la colocación de los dedos en posiciones altas periódicamente. Tu oído se desarrollará más rápido.\n\n• Progresión con Metrónomo: Al practicar escalas o pasajes difíciles, reduce el BPM del Metrónomo a 60. Aumenta el tempo solo cuando repitas la secuencia perfectamente 5 veces.",

    "smart_tuner_header" to "AFINADOR INTELIGENTE",
    "tuner_subtitle" to "Afinación Precisa y Referencia de Tono",
    "auto_string_detect" to "DETECCIÓN AUTOMÁTICA DE CUERDA",
    "auto_detect_desc" to "Fija frecuencias automáticamente",
    "mic_permission_error" to "Se requiere permiso de micrófono para afinar",
    "select_string_prompt" to "Selecciona una cuerda abajo",
    "reference_playback" to "Reproducción de Referencia",
    "perfectly_in_tune" to "PERFECTAMENTE AFINADO",
    "stop_synth_sound" to "Detener Sonido Sintetizado",
    "play_reference_tone" to "Reproducir Tono de Referencia",
    "start_listen_mode" to "INICIAR MODO DE ESCUCHA PRECISA",
    "stop_mic_listen" to "DETENER ESCUCHA DEL MICRÓFONO",
    "cents_flat" to "BEMOL",
    "cents_sharp" to "SOSTENIDO",
    "config_button" to "⚙",
    "config_sheet_title" to "CONFIGURACIÓN DEL AFINADOR",
    "config_reference_pitch" to "Tono de Referencia A4 (Hz)",
    "config_max_cents" to "Rango del Medidor (cents)",
    "config_save_preset" to "GUARDAR COMO PRESET",
    "config_save_hint" to "Nombre del preset",
    "config_my_presets" to "MIS PRESETS",
    "config_no_presets" to "Sin presets guardados",
    "config_load" to "CARGAR",
    "config_delete" to "ELIMINAR",
    "config_close" to "CERRAR",

    "metronome_header" to "METRÓNOMO",
    "metronome_subtitle" to "Entrenador de Pulso Rítmico",
    "bpm_tempo_label" to "BPM (TEMPO)",
    "tap_tempo_button" to "TAP TEMPO",
    "time_signature_label" to "COMPÁS",
    "downbeat_accent_label" to "ACENTO DEL PULSO",
    "accent_on" to "ACENTO ACTIVADO",
    "accent_off" to "ACENTO DESACTIVADO",
    "pause_pulse" to "PAUSAR PULSO",
    "play_metronome" to "INICIAR METRÓNOMO",
    "decrement_bpm_cd" to "Reducir BPM",
    "increment_bpm_cd" to "Aumentar BPM",

    "app_title_auth" to "VIOLIN STUDIO PRO",
    "shield_security_logo" to "Logo de Escudo de Seguridad",

    "video_record" to "Grabar",
    "video_stop" to "Detener",
    "video_recording" to "Grabando...",
    "video_compressing" to "Comprimiendo video...",
    "video_uploading" to "Subiendo...",
    "video_send" to "Enviar al Chat",
    "video_cancel" to "Cancelar",
    "video_retry" to "Reintentar",
    "video_record_button" to "Grabar Video",
    "video_upload_success" to "¡Video subido exitosamente!",
    "video_time_remaining" to "Tiempo restante:",
    "video_permission_title" to "Acceso a la Cámara Requerido",
    "video_permission_rationale" to "Se necesita acceso a la cámara para grabar videos de demostración para tus estudiantes.",
    "video_permission_grant" to "Conceder Acceso",
    "video_permission_deny" to "Ahora No",
    "video_permission_required" to "Se requiere permiso de cámara para grabar videos. Concede acceso en Ajustes.",

    "blur_processing" to "Protegiendo identidad...",
    "blur_progress" to "Procesando frame %1\$d/%2\$d",
    "blur_warning" to "No se pudo aplicar el difuminado facial. Video enviado sin difuminar.",
    "blur_disabled" to "Difuminado no requerido (usuario adulto)"
  )
}
