package com.violinmaster.app.ui.theme

object StringsLessons {
  val en = mapOf(
    "learning_journey_progress" to "LEARNING JOURNEY PROGRESS",
    "modules_passed" to "Modules Passed",
    "total_bow_time" to "Total bow time",
    "level_prefix" to "Level:",
    "minutes_practiced" to "m practiced",
    "stage_learning_objectives" to "STAGE LEARNING OBJECTIVES:",
    "included_core_drills" to "INCLUDED CORE DRILLS:",
    "select_current_string" to "SELECT CURRENT VIOLIN STRING:",
    "string_label" to "String",
    "virtual_fingerboard" to "VIRTUAL FINGERBOARD GRAPHIC (1st Position Tapes):",
    "position_relative_tape" to "Position relative tape",
    "string_target" to "String: Target",
    "frequency_match" to "Frequency match:",
    "listen_and_match" to "Listen and match the pitch with your physical violin first position fingers.",

    "modules_progress_format" to "%d of %d Modules Passed",
    "total_bow_time_format" to "Total bow time: %dm practiced",
    "level_format" to "Level: %s",
    "syllabus_suffix" to "%s SYLLABUS",
    "minutes_practiced_format" to "%dm practiced",
    "lesson_completed_button" to "Completed",
    "mark_done_button" to "Mark Done",
    "practicing_label" to "PRACTICING",
    "drill_time_button" to "DRILL TIME",
    "string_label_format" to "%s String",
    "note_frequency_format" to "%s (%d Hz)",
    "string_target_format" to "%s-String: Target %s",
    "frequency_match_format" to "Frequency match: %s Hz",
    "video_instructor_prefix" to "Instructor: ",
    "video_duration_prefix" to "Video Duration: ",
    "secure_time_format" to "SECURE TIME: %02d:%02d",
    "close_stream_button" to "Close Stream",
    "secure_stream_cdn_label" to "AES-256 CDN Stream",
    "practice_log_format" to "practiced %d mins",
    "delete_log_cd" to "Delete practice log",
    "student_prefix" to "STUDENT: ",
    "streak_days_format" to "%d Days",
    "average_format" to "%.1f m",
    "video_demo_format" to "Video Demo: %ds",
    "stats_analytics_title" to "Weekly Practice Balance",
    "stats_leaderboard_title" to "Global Rankings",
    "pending_label" to "PENDING",
    "video_title_placeholder" to "Video Title (e.g. Vibrato Bowing Guide)",
    "resource_target_protocol" to "Resource Target Protocol:",
    "access_ticket_expiry" to "Access Ticket Lease Expiry Epoch:",
    "lease_valid" to " (Lease valid)",
    "dynamic_crypto_nonce" to "Dynamic Crypto Nonce Code:",
    "hmac_sha256_signature" to "HMAC SHA-256 Access Ticket Signature:",
    "encouragement_seed" to "Seed your skills! Focus on straight open string bows.",
    "encouragement_warm" to "Warm resonance growing! Practice shifts carefully.",
    "encouragement_habits" to "Outstanding habits! Your double stops sound magnificent.",
    "encouragement_virtuoso" to "Virtuoso level! A master academic scholar of the acoustic violin.",

    "chat_title" to "Chat",
    "chat_button" to "Open Chat",
    "chat_input_hint" to "Type a message...",
    "chat_empty" to "No messages yet. Start the conversation!",
    "chat_send" to "Send message",
    "chat_today" to "Today",
    "chat_yesterday" to "Yesterday",
    "chat_attachment_video" to "Video attachment",
    "back_button" to "Back",

    "secure_student_pin" to "SECURE STUDENT ACCOUNT PIN",
    "secure_pin_desc" to "Create a master numeric passcode. Passwords are never stored in plain-text. They are hashed cryptographically with a unique secure salt to ensure extreme user data privacy.",
    "enter_vault_pin" to "ENTER PRIVATE VAULT PIN",
    "vault_pin_desc" to "Locked Area: Premium masterclass modules require authorized decryption confirmation. Enter your four-digit secure account passcode.",
    "secure_video_decryption" to "SECURE VIDEO DECRYPTION LIVE",
    "authorized_access_confirmed" to "Authorized access is confirmed. Playback streams generate dynamic, cryptographically signed signed-ticket tokens with a 60-second automatic API expiration lease.",
    "academy_lecture_modules" to "ACADEMY LECTURE MODULES",
    "logout_vault" to "Logout Vault",
    "active_secure_stream" to "ACTIVE SECURE STREAM",
    "live_decrypting" to "LIVE DECRYPTING PLAYBACK... [OK]",
    "decrypt_interaction_logs" to "DECRYPT INTERACTION SECURITY LOGS",
    "secure_practice_protects" to "Secure practice protects videos against credential harvesting or sniffing. Here is the single-use signed streaming ticket generated for this lesson session.",
    "cdn_signature_verified" to "CDN signature validation status: [VERIFIED]",

    "theory_quest_quiz" to "Theory Quest & Quizzes",
    "theory_quiz_desc" to "Test your technical violin literacy and unlock performance badges with instant analysis.",
    "premium_masterclass" to "Premium Masterclass: Access restricted video tutorials secured via cryptographic salt & signed URL tickets.",
    "teacher_tab_desc" to "Distribute predefined curriculum plans, audit video demonstration bounds, and manage student accounts.",
    "student_tab_desc" to "View exercises assigned exclusively by your instructor, study tutorial videos, and track your progress.",
    "freelancer_tab_desc" to "Track your levels, complete explicit learning objectives, and start targeted bowing drills.",
    "verify_answer" to "VERIFY ANSWER",
    "next_question" to "NEXT QUESTION",
    "show_finished_summary" to "SHOW FINISHED SUMMARY",
    "theory_quiz_completed" to "Theory Quiz Completed!",
    "you_scored" to "You scored %d points out of 100",
    "theory_badge_title" to "Theory Academic Master Badge",
    "theory_badge_desc" to "Perfect technical literacy unlocked!",
    "try_again" to "TRY AGAIN",
    "v_excellent_guess" to "✓ Excellent Guess!",
    "x_correction" to "✗ Correction!"
  )

  val es = mapOf(
    "learning_journey_progress" to "PROGRESO DEL VIAJE DE APRENDIZAJE",
    "modules_passed" to "Módulos Aprobados",
    "total_bow_time" to "Tiempo total de arco",
    "level_prefix" to "Nivel:",
    "minutes_practiced" to "m practicados",
    "stage_learning_objectives" to "OBJETIVOS DE APRENDIZAJE:",
    "included_core_drills" to "EJERCICIOS INCLUIDOS:",
    "select_current_string" to "SELECCIONAR CUERDA ACTUAL:",
    "string_label" to "Cuerda",
    "virtual_fingerboard" to "DIAGRAMA VIRTUAL DEL DIAPASÓN (Cintas de 1ª Posición):",
    "position_relative_tape" to "Cinta de posición relativa",
    "string_target" to "Cuerda: Objetivo",
    "frequency_match" to "Frecuencia coincidente:",
    "listen_and_match" to "Escucha e iguala el tono con los dedos de tu violín físico en primera posición.",

    "modules_progress_format" to "%d de %d Módulos Aprobados",
    "total_bow_time_format" to "Tiempo total de arco: %dm practicados",
    "level_format" to "Nivel: %s",
    "syllabus_suffix" to "%s SÍLABO",
    "minutes_practiced_format" to "%dm practicados",
    "lesson_completed_button" to "Completado",
    "mark_done_button" to "Marcar Hecho",
    "practicing_label" to "PRACTICANDO",
    "drill_time_button" to "EJERCITAR",
    "string_label_format" to "Cuerda %s",
    "note_frequency_format" to "%s (%d Hz)",
    "string_target_format" to "Cuerda-%s: Objetivo %s",
    "frequency_match_format" to "Frecuencia coincidente: %s Hz",
    "video_instructor_prefix" to "Instructor: ",
    "video_duration_prefix" to "Duración del Video: ",
    "secure_time_format" to "TIEMPO SEGURO: %02d:%02d",
    "close_stream_button" to "Cerrar Transmisión",
    "secure_stream_cdn_label" to "Transmisión CDN AES-256",
    "practice_log_format" to "practicado %d mins",
    "delete_log_cd" to "Eliminar registro de práctica",
    "student_prefix" to "ESTUDIANTE: ",
    "streak_days_format" to "%d Días",
    "average_format" to "%.1f m",
    "video_demo_format" to "Video Demo: %ds",
    "stats_analytics_title" to "Balance Semanal de Práctica",
    "stats_leaderboard_title" to "Clasificación Global",
    "pending_label" to "PENDIENTE",
    "video_title_placeholder" to "Título del Video (ej. Guía de Vibrato)",
    "resource_target_protocol" to "Protocolo de Recurso Objetivo:",
    "access_ticket_expiry" to "Expiración del Ticket de Acceso:",
    "lease_valid" to " (Válido)",
    "dynamic_crypto_nonce" to "Código Criptográfico Dinámico:",
    "hmac_sha256_signature" to "Firma HMAC SHA-256 del Ticket:",
    "encouragement_seed" to "Planta tus habilidades. Concéntrate en arcos rectos de cuerdas al aire.",
    "encouragement_warm" to "La resonancia cálida crece. Practica los cambios con cuidado.",
    "encouragement_habits" to "Hábitos excepcionales. Tus dobles cuerdas suenan magníficas.",
    "encouragement_virtuoso" to "Nivel virtuoso. Un maestro académico del violín acústico.",

    "chat_title" to "Chat",
    "chat_button" to "Abrir Chat",
    "chat_input_hint" to "Escribe un mensaje...",
    "chat_empty" to "Aún no hay mensajes. ¡Inicia la conversación!",
    "chat_send" to "Enviar mensaje",
    "chat_today" to "Hoy",
    "chat_yesterday" to "Ayer",
    "chat_attachment_video" to "Video adjunto",
    "back_button" to "Volver",

    "secure_student_pin" to "PIN SEGURO DE CUENTA",
    "secure_pin_desc" to "Crea un código de acceso numérico maestro. Las contraseñas nunca se almacenan en texto plano. Se procesan criptográficamente con una sal única segura para garantizar la máxima privacidad de los datos del usuario.",
    "enter_vault_pin" to "INGRESAR PIN DE LA BÓVEDA",
    "vault_pin_desc" to "Área Bloqueada: Los módulos de clase magistral premium requieren confirmación de descifrado autorizado. Ingresa tu código de acceso seguro de cuatro dígitos.",
    "secure_video_decryption" to "DESCIFRADO SEGURO DE VIDEO EN VIVO",
    "authorized_access_confirmed" to "Acceso autorizado confirmado. Las transmisiones de reproducción generan tokens de tickets firmados criptográficamente con una caducidad automática de 60 segundos.",
    "academy_lecture_modules" to "MÓDULOS DE CONFERENCIAS ACADÉMICAS",
    "logout_vault" to "Cerrar Bóveda",
    "active_secure_stream" to "TRANSMISIÓN SEGURA ACTIVA",
    "live_decrypting" to "DESCIFRANDO REPRODUCCIÓN EN VIVO... [OK]",
    "decrypt_interaction_logs" to "REGISTROS DE INTERACCIÓN DE DESCIFRADO",
    "secure_practice_protects" to "La práctica segura protege los videos contra la captura de credenciales. Este es el ticket de transmisión firmado de un solo uso generado para esta sesión de lección.",
    "cdn_signature_verified" to "Estado de validación de firma CDN: [VERIFICADO]",

    "theory_quest_quiz" to "Misiones Teóricas y Cuestionarios",
    "theory_quiz_desc" to "Pon a prueba tus conocimientos técnicos de violín y desbloquea insignias con análisis instantáneo.",
    "premium_masterclass" to "Clase Magistral Premium: Accede a tutoriales de video restringidos mediante firma criptográfica de tickets de URL.",
    "teacher_tab_desc" to "Distribuye planes de estudio predefinidos, audita demostraciones en video y gestiona cuentas de estudiantes.",
    "student_tab_desc" to "Consulta los ejercicios que te ha asignado tu profesor en exclusiva, visualiza tutoriales en video y sigue tu evolución.",
    "freelancer_tab_desc" to "Haz un seguimiento de tus niveles, cumple directrices prácticas y comienza ejercicios avanzados de arco.",
    "verify_answer" to "VERIFICAR RESPUESTA",
    "next_question" to "SIGUIENTE PREGUNTA",
    "show_finished_summary" to "VER RESUMEN FINAL",
    "theory_quiz_completed" to "¡Cuestionario de Teoría Completado!",
    "you_scored" to "Has obtenido %d puntos de 100",
    "theory_badge_title" to "Insignia de Maestro Académico de Teoría",
    "theory_badge_desc" to "¡Conocimientos técnicos perfectos desbloqueados!",
    "try_again" to "INTENTAR DE NUEVO",
    "v_excellent_guess" to "¡✓ Respuesta Excelente!",
    "x_correction" to "¡✗ Corrección!"
  )
}
