package com.violinmaster.app.ui.theme

object StringsHome {
  val en = mapOf(
    "app_name" to "Violin Master Pro",
    "tab_home" to "Home",
    "tab_lessons" to "Lessons",
    "tab_stats" to "Progress",
    "tab_settings" to "Settings",

    "welcome" to "Welcome back, Maestro!",
    "goal_progress" to "Daily Goal Progress",
    "no_goal" to "Setup a goal inside the settings panel.",
    "goal_achieved" to "Goal achieved! Incredible discipline! 🎉",
    "start_practice_now" to "START PRACTICE SESSION",
    "stop_save" to "STOP & SAVE SESSION",
    "quick_utilities" to "QUICK ASSISTANT TOOLS",
    "smart_tuner" to "Smart Tuner",
    "harmonic_metronome" to "Metronome",
    "tuner_desc" to "Play open strings to debug pitch & tuning",
    "metronome_desc" to "Configure tempo beat triggers & visual swing",
    "current_active_practice" to "Current Practice Topic:",
    "general_practice" to "General Practice",
    "daily_goal_title" to "DAILY GOAL",
    "active_practice_label" to "ACTIVE PRACTICE SESSION",
    "quick_tools_label" to "QUICK TOOLS",
    "recommended_drill_label" to "RECOMMENDED DRILL",
    "current_badge" to "CURRENT",
    "module_3_label" to "MODULE 3",
    "advanced_bowing_title" to "Advanced Bowing Techniques",
    "advanced_bowing_desc" to "Mastering the 'Détaché' and 'Martelé' strokes for cleaner transitions and dynamic range.",
    "save_and_log_button" to "Save & Log",
    "discard_button" to "Discard",
    "practicing_now_label" to "PRACTICING NOW",
    "resume_practice_button" to "RESUME PRACTICE",
    "cancel_button" to "CANCEL",
    "save_practice_cd" to "Save Practice",
    "cancel_practice_cd" to "Cancel Practice",

    "daily_tasks_title" to "DAILY TASKS",
    "leaderboard_title" to "GLOBAL LEADERBOARD",
    "rank_label" to "Rank",
    "points_label" to "Points",
    "points_suffix" to "pts",
    "skill_level_label" to "DIFFICULTY LEVEL",
    "skill_beginner" to "Beginner",
    "skill_intermediate" to "Intermediate",
    "skill_advanced" to "Advanced",
    "attempts_needed_title" to "Task Completed!",
    "attempts_needed_subtitle" to "How many attempts did you need?",
    "attempt_1" to "1 attempt (100 pts)",
    "attempt_2" to "2 attempts (75 pts)",
    "attempt_3" to "3 attempts (50 pts)",
    "attempt_4" to "4+ attempts (25 pts)",
    "confirm_completion" to "CONFIRM COMPLETION",
    "start_task" to "START",
    "completed_btn" to "COMPLETED",
    "analytics_sub_tab" to "ANALYTICS",
    "ranking_sub_tab" to "LEADERBOARD",
    "level_title" to "Skill Level",
    "take_quiz_button" to "Take Quiz",

    "practice_streak" to "PRACTICE STREAK",
    "daily_average" to "DAILY AVERAGE",
    "practice_drill_trend" to "PRACTICE DRILL TREND (MINS)",
    "completed_practice_journal" to "COMPLETED PRACTICE JOURNAL",
    "empty_log_book" to "Your log book is empty. Complete a practice module or sound tuning reference to log stats!",

    "active_label" to "ACTIVE",
    "no_previous_history" to "No previous history logs.",
    "attached_video_label_short" to "Attached video:"
  )

  val es = mapOf(
    "app_name" to "Maestro de Violín Pro",
    "tab_home" to "Inicio",
    "tab_lessons" to "Lecciones",
    "tab_stats" to "Progreso",
    "tab_settings" to "Ajustes",

    "welcome" to "¡Bienvenido, Maestro!",
    "goal_progress" to "Meta Diaria de Práctica",
    "no_goal" to "Configura una meta diaria en la pestaña de ajustes.",
    "goal_achieved" to "¡Meta cumplida! ¡Disciplina increíble! 🎉",
    "start_practice_now" to "INICIAR SESIÓN DE PRÁCTICA",
    "stop_save" to "DETENER Y GUARDAR SESIÓN",
    "quick_utilities" to "HERRAMIENTAS AUXILIARES",
    "smart_tuner" to "Afinador Inteligente",
    "harmonic_metronome" to "Metrónomo",
    "tuner_desc" to "Toca cuerdas al aire para calibrar la entonación",
    "metronome_desc" to "Configura el tempo, silencios y movimiento visual",
    "current_active_practice" to "Tema de Práctica Activo:",
    "general_practice" to "Práctica General",
    "daily_goal_title" to "META DIARIA",
    "active_practice_label" to "SESIÓN DE PRÁCTICA ACTIVA",
    "quick_tools_label" to "HERRAMIENTAS RÁPIDAS",
    "recommended_drill_label" to "EJERCICIO RECOMENDADO",
    "current_badge" to "ACTUAL",
    "module_3_label" to "MÓDULO 3",
    "advanced_bowing_title" to "Técnicas Avanzadas de Arco",
    "advanced_bowing_desc" to "Dominando los golpes de arco 'Détaché' y 'Martelé' para transiciones más limpias y rango dinámico.",
    "save_and_log_button" to "Guardar y Registrar",
    "discard_button" to "Descartar",
    "practicing_now_label" to "PRACTICANDO AHORA",
    "resume_practice_button" to "REANUDAR PRÁCTICA",
    "cancel_button" to "CANCELAR",
    "save_practice_cd" to "Guardar Práctica",
    "cancel_practice_cd" to "Cancelar Práctica",

    "daily_tasks_title" to "TAREAS DIARIAS",
    "leaderboard_title" to "CLASIFICACIÓN GLOBAL",
    "rank_label" to "Puesto",
    "points_label" to "Puntos",
    "points_suffix" to "pts",
    "skill_level_label" to "NIVEL DE HABILIDAD",
    "skill_beginner" to "Principiante",
    "skill_intermediate" to "Intermedio",
    "skill_advanced" to "Avanzado",
    "attempts_needed_title" to "¡Tarea Completada!",
    "attempts_needed_subtitle" to "¿Cuántos intentos has necesitado?",
    "attempt_1" to "1 intento (100 pts)",
    "attempt_2" to "2 intentos (75 pts)",
    "attempt_3" to "3 intentos (50 pts)",
    "attempt_4" to "4+ intentos (25 pts)",
    "confirm_completion" to "CONFIRMAR",
    "start_task" to "COMENZAR",
    "completed_btn" to "COMPLETADO",
    "analytics_sub_tab" to "ESTADÍSTICAS",
    "ranking_sub_tab" to "CLASIFICACIÓN",
    "level_title" to "Nivel de Habilidad",
    "take_quiz_button" to "Tomar Cuestionario",

    "practice_streak" to "RACHA DE PRÁCTICA",
    "daily_average" to "PROMEDIO DIARIO",
    "practice_drill_trend" to "TENDENCIA DE PRÁCTICA (MINS)",
    "completed_practice_journal" to "DIARIO DE PRÁCTICA COMPLETADO",
    "empty_log_book" to "Tu libro de registro está vacío. ¡Completa un módulo de práctica o una referencia de afinación para registrar estadísticas!",

    "active_label" to "ACTIVO",
    "no_previous_history" to "Sin registros de historial previos.",
    "attached_video_label_short" to "Video adjunto:"
  )
}
