package com.violinmaster.app.ui.theme

object StringsAuth {
  val en = mapOf(
    "login_required" to "Violin Studio Authentication",
    "username_label" to "User Account ID",
    "password_label" to "Private Cryptographic Pin",
    "role_label" to "Choose Academic Role",
    "role_teacher" to "Teacher/Instructor",
    "role_student" to "Student/Apprentice",
    "role_freelancer" to "Freelancer/Autodidact",
    "birth_year_label" to "Year of Birth",
    "birth_year_hint" to "Select your birth year",
    "error_birth_year_invalid" to "Please select a valid birth year",
    "register_desc" to "Create account with a secure passcode",
    "login_info_desc" to "Enter credentials to unlock lesson archives",
    "pin_hint" to "Enter 4 digits",
    "btn_login" to "Log In Account",
    "btn_register" to "Register Profile",
    "switch_to_reg" to "Don't have an account? Register here",
    "switch_to_log" to "Already have an account? Sign In",

    "teacher_dashboard_title" to "Teacher Command Studio",
    "your_code_label" to "Your Teacher Invite Code:",
    "copy_code_tip" to "Students use this code upon registering to link to you.",
    "send_assignment" to "ASSIGN NEW OBJECTIVE",
    "select_student" to "Designee Student:",
    "all_students" to "All Connected Students",
    "assignment_title_hint" to "Assignment Title (e.g. Vibrato Slow-Wave)",
    "assignment_desc_hint" to "Warm-up steps, repetitions & goals...",
    "attach_video_label" to "Attach Optional Demonstration Video:",
    "attachment_allowed" to "Attach Video (Max 3 Mins)",
    "detach_video" to "Remove Video Attachment",
    "duration_sec_label" to "Simulated Video Length (Seconds):",
    "video_time_limit" to "Video exceeds maximum length of 3 minutes (180s)!",
    "btn_submit_assignment" to "Disseminate Assignment",
    "predefined_templates" to "PREDEFINED LESSON PLAN TEMPLATES",
    "temp_posture" to "Shoulder and Chinrest Alignment Checks",
    "temp_res" to "Sympathetic Resonance Checks in D Major",
    "temp_bounce" to "Spiccato Wood Equilibrium Gravity Bounce",
    "sent_assignments_log" to "DELIVERED ASSIGNMENTS LOG",
    "delete_task" to "Delete Task",

    "student_dashboard_title" to "Student Practice Hub",
    "link_teacher_title" to "LINK INSTRUCTOR CODE",
    "link_teacher_desc" to "Input your instructor's invite code to fetch assigned tasks.",
    "input_code_hint" to "Enter Teacher Code (e.g. TEACH-XXXX)",
    "btn_link_teacher" to "Link Instructor",
    "linked_to_teacher" to "Connected and verified with: ",
    "instructor_name_placeholder" to "Instructor",
    "no_assignments" to "Your teacher hasn't published any assignments yet. Keep practicing with open tools!",
    "assigned_by" to "Assigned by: ",
    "btn_complete" to "Submit Completion Log",
    "completed_tag" to "COMPLETED",
    "play_sim_video" to "Play Demonstration Video",
    "assignments_section_title" to "YOUR ACADEMIC ASSIGNMENTS",

    "lessons_header_freelancer" to "Violin Curriculum",

    "error_username_empty" to "Username cannot be empty.",
    "error_pin_length" to "Passcode PIN must be exactly 4 digits.",
    "error_login_failed" to "Incorrect username or security PIN.",
    "error_user_exists" to "User already registered. Please login.",
    "success_register" to "Account secured! Log in now.",

    "forgot_pin" to "Forgot PIN?",
    "sign_in_with_google" to "Sign in with Google",
    "recovery_enter_username" to "Enter your username to recover",
    "recovery_question_label" to "Security question",
    "recovery_answer_hint" to "Your answer",
    "recovery_set_new_pin" to "Set a new PIN",
    "recovery_wrong_answer" to "Incorrect answer",
    "recovery_locked" to "Too many attempts. Try again in {0} minutes.",
    "recovery_success" to "PIN reset successful!",
    "recovery_google_sign_in" to "Sign in with Google",
    "recovery_no_question" to "Recovery not configured. Use Google Sign-In.",

    "recovery_q_first_pet" to "What was the name of your first pet?",
    "recovery_q_birth_city" to "In what city were you born?",
    "recovery_q_favorite_teacher" to "Who was your favorite teacher?",
    "recovery_q_childhood_nickname" to "What was your childhood nickname?",
    "recovery_q_first_instrument" to "What was your first musical instrument?"
  )

  val es = mapOf(
    "login_required" to "Autenticación de Violin Studio",
    "username_label" to "ID de la Cuenta de Usuario",
    "password_label" to "PIN de Seguridad Privado",
    "role_label" to "Elige tu Rol Académico",
    "role_teacher" to "Profesor / Instructor",
    "role_student" to "Estudiante / Aprendiz",
    "role_freelancer" to "Freelancer / Autodidacta",
    "birth_year_label" to "Año de Nacimiento",
    "birth_year_hint" to "Selecciona tu año de nacimiento",
    "error_birth_year_invalid" to "Selecciona un año de nacimiento válido",
    "register_desc" to "Crea una cuenta con un PIN cifrado seguro",
    "login_info_desc" to "Inicia sesión para desbloquear las lecciones",
    "pin_hint" to "Introduce 4 dígitos",
    "btn_login" to "Iniciar Sesión",
    "btn_register" to "Registrar Cuenta",
    "switch_to_reg" to "¿No tienes cuenta? Regístrate aquí",
    "switch_to_log" to "¿Ya tienes cuenta? Inicia Sesión",

    "teacher_dashboard_title" to "Panel de Control del Instructor",
    "your_code_label" to "Tu Código de Invitación de Profesor:",
    "copy_code_tip" to "Los estudiantes usan este código al registrarse para vincularse contigo.",
    "send_assignment" to "ENVIAR NUEVA TAREA",
    "select_student" to "Asignar al estudiante:",
    "all_students" to "Todos los Estudiantes Vinculados",
    "assignment_title_hint" to "Título de la Tarea (ej. Vibrato Lento)",
    "assignment_desc_hint" to "Pasos de calentamiento, repeticiones y metas...",
    "attach_video_label" to "Adjuntar Video de Demostración Opcional:",
    "attachment_allowed" to "Adjuntar un Video (Máx 3 Minutos)",
    "detach_video" to "Quitar Video Adjunto",
    "duration_sec_label" to "Duración Regulada del Video (Segundos):",
    "video_time_limit" to "¡El video supera el límite de 3 minutos (180s)!",
    "btn_submit_assignment" to "Publicar y Enviar Tarea",
    "predefined_templates" to "PLANTILLAS DE LECCIONES PREDEFINIDAS",
    "temp_posture" to "Alineación y Calibración de Postura del Violín",
    "temp_res" to "Prácticas de Resonancia en Re Mayor",
    "temp_bounce" to "Punto de Equilibrio y Rebote del Arco (Spiccato)",
    "sent_assignments_log" to "HISTORIAL DE TAREAS ENVIADAS",
    "delete_task" to "Eliminar Tarea",

    "student_dashboard_title" to "Centro de Práctica del Estudiante",
    "link_teacher_title" to "VINCULAR CÓDIGO DEL PROFESOR",
    "link_teacher_desc" to "Escribe el código de invitación de tu profesor para recibir tus asignaciones.",
    "input_code_hint" to "Introduce el Código (ej. TEACH-XXXX)",
    "btn_link_teacher" to "Vincular Profesor",
    "linked_to_teacher" to "Conectado y verificado con: ",
    "instructor_name_placeholder" to "Instructor",
    "no_assignments" to "Tu profesor no ha enviado tareas aún. ¡Sigue practicando con las herramientas libres!",
    "assigned_by" to "Asignado por: ",
    "btn_complete" to "Marcar como Completado",
    "completed_tag" to "COMPLETADO",
    "play_sim_video" to "Reproducir Video de Demostración",
    "assignments_section_title" to "TUS TAREAS ACADÉMICAS",

    "lessons_header_freelancer" to "Plan Curricular de Violín",

    "error_username_empty" to "El ID de usuario no puede estar vacío.",
    "error_pin_length" to "El PIN debe ser exactamente de 4 dígitos.",
    "error_login_failed" to "ID de usuario o PIN de seguridad incorrecto.",
    "error_user_exists" to "El usuario ya está registrado. Inicie sesión.",
    "success_register" to "¡Cuenta registrada! Ya puedes iniciar sesión.",

    "forgot_pin" to "¿Olvidaste tu PIN?",
    "recovery_enter_username" to "Ingresá tu usuario para recuperar",
    "recovery_question_label" to "Pregunta de seguridad",
    "recovery_answer_hint" to "Tu respuesta",
    "recovery_set_new_pin" to "Creá un nuevo PIN",
    "recovery_wrong_answer" to "Respuesta incorrecta",
    "recovery_locked" to "Demasiados intentos. Probá de nuevo en {0} minutos.",
    "recovery_success" to "¡PIN restablecido!",
    "recovery_google_sign_in" to "Iniciar sesión con Google",
    "recovery_no_question" to "Recuperación no configurada. Usá Google Sign-In.",

    "recovery_q_first_pet" to "¿Cómo se llamaba tu primera mascota?",
    "recovery_q_birth_city" to "¿En qué ciudad naciste?",
    "recovery_q_favorite_teacher" to "¿Quién fue tu profesor/a favorito/a?",
    "recovery_q_childhood_nickname" to "¿Cuál era tu apodo de la infancia?",
    "recovery_q_first_instrument" to "¿Cuál fue tu primer instrumento musical?"
  )
}
